// <auto-generated />
using System;
using Chat.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chat.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260104110107_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chat.Domain.Persistence.ChatReassignmentHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewAssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OldAssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReassignedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ChatReassignmentHistory", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FromDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserModelId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserModelId");

                    b.HasIndex("UserModelId1");

                    b.ToTable("ChatRequests", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.MessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatRequestModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatRequestModelId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserModelId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDepartmentAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentModelId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.UserModel", null)
                        .WithMany("AssignedChats")
                        .HasForeignKey("UserModelId");

                    b.HasOne("Chat.Domain.Persistence.UserModel", null)
                        .WithMany("CreatedChats")
                        .HasForeignKey("UserModelId1");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.MessageModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.ChatRequestModel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRequestModelId");

                    b.HasOne("Chat.Domain.Persistence.UserModel", null)
                        .WithMany("SentMessages")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.DepartmentModel", null)
                        .WithMany("Users")
                        .HasForeignKey("DepartmentModelId");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.DepartmentModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.Navigation("AssignedChats");

                    b.Navigation("CreatedChats");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
