// <auto-generated />
using System;
using Chat.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chat.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260116132824_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chat.Domain.Persistence.ChatReassignmentHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewAssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewToDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OldAssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OldToDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReassignedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatRequestId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NewAssignedUserId");

                    b.HasIndex("OldAssignedUserId");

                    b.HasIndex("ReassignedByUserId");

                    b.ToTable("ChatReassignmentHistory", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FromDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ChatRequests", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.DepartmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.MessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatRequestId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDepartmentAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatReassignmentHistoryModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.ChatRequestModel", "ChatRequest")
                        .WithMany("ReassignmentHistory")
                        .HasForeignKey("ChatRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat.Domain.Persistence.UserModel", "NewAssignedUser")
                        .WithMany()
                        .HasForeignKey("NewAssignedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat.Domain.Persistence.UserModel", "OldAssignedUser")
                        .WithMany()
                        .HasForeignKey("OldAssignedUserId");

                    b.HasOne("Chat.Domain.Persistence.UserModel", "ReassignedByUser")
                        .WithMany()
                        .HasForeignKey("ReassignedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRequest");

                    b.Navigation("NewAssignedUser");

                    b.Navigation("OldAssignedUser");

                    b.Navigation("ReassignedByUser");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.UserModel", "AssignedToUser")
                        .WithMany("AssignedChats")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chat.Domain.Persistence.UserModel", "CreatedByUser")
                        .WithMany("CreatedChats")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.MessageModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.ChatRequestModel", "ChatRequest")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat.Domain.Persistence.UserModel", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRequest");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.HasOne("Chat.Domain.Persistence.DepartmentModel", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.ChatRequestModel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ReassignmentHistory");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.DepartmentModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Chat.Domain.Persistence.UserModel", b =>
                {
                    b.Navigation("AssignedChats");

                    b.Navigation("CreatedChats");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
